services:
  api:
    container_name: drizzle_backend
    build: .
    ports:
      - 8000:8000
    env_file: "./.env"
    environment:
      POSTGRES_HOST: db

    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: ./
          target: /app
          action: sync

    depends_on:
      - db

  db:
    container_name: drizzle_database
    image: postgres:latest
    env_file: "./.env"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: drizzle_postgres_data
