services:
  api:
    container_name: django_storage_api
    build: ./backend
    ports:
      - 8000:8000
    env_file: "./backend/.env"
    environment:
      POSTGRES_HOST: db
      S3_ENDPOINT_URL: "http://s3:9000"
    develop:
      watch:
        - path: ./requirements.txt
          action: rebuild
        - path: ./backend
          target: /app
          action: sync
    depends_on:
      - db
      - s3

  web:
    container_name: django_storage_web
    build: ./frontend
    ports:
      - 3000:3000
    env_file: "./frontend/.env.local"
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
    depends_on:
      - api

  s3:
    container_name: django_storage_s3
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    env_file: "./backend/.env"
    command: server /data --console-address ":9001"
    volumes:
      - s3_data:/data

  db:
    container_name: django_storage_db
    image: postgres:latest
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
    name: django_storage-postgres-volume
  s3_data:
    name: django_storage-volume
