services:
  db:
    image: redis/redis-stack:latest
    container_name: redis_db
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-db:/data

volumes:
  redis-db:
    name: redis-db-test
