services:
  db:
    image: redis/redis-stack:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis-db:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/db

volumes:
  redis-db:
    name: redis-db-test
  redisinsight:
    name: redisinsight-test
